// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP6wr_3EW2Y06bz1Oz7A6BwYLRu7KXMek',
    appId: '1:908165698905:web:cde2797c7bb27e836ee848',
    messagingSenderId: '908165698905',
    projectId: 'project2-eaaae',
    authDomain: 'project2-eaaae.firebaseapp.com',
    storageBucket: 'project2-eaaae.appspot.com',
    measurementId: 'G-72LK6E6H78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-DUQI4EAb2sZYyzvZ4KPedcmYvAmWPII',
    appId: '1:908165698905:android:e8d53fa1441855d46ee848',
    messagingSenderId: '908165698905',
    projectId: 'project2-eaaae',
    storageBucket: 'project2-eaaae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVUli1EG75zLskaMwO9CWmRh16A-4NKU0',
    appId: '1:908165698905:ios:6be7248dd1beba0d6ee848',
    messagingSenderId: '908165698905',
    projectId: 'project2-eaaae',
    storageBucket: 'project2-eaaae.appspot.com',
    iosBundleId: 'com.example.fp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVUli1EG75zLskaMwO9CWmRh16A-4NKU0',
    appId: '1:908165698905:ios:6be7248dd1beba0d6ee848',
    messagingSenderId: '908165698905',
    projectId: 'project2-eaaae',
    storageBucket: 'project2-eaaae.appspot.com',
    iosBundleId: 'com.example.fp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP6wr_3EW2Y06bz1Oz7A6BwYLRu7KXMek',
    appId: '1:908165698905:web:67fb9267f1f09f506ee848',
    messagingSenderId: '908165698905',
    projectId: 'project2-eaaae',
    authDomain: 'project2-eaaae.firebaseapp.com',
    storageBucket: 'project2-eaaae.appspot.com',
    measurementId: 'G-QEZ8309H7K',
  );

}